version: '3'
services:
  bo-proxy-prod:
    image: 564094729738.dkr.ecr.us-east-1.amazonaws.com/tg-bo/nginx:pr_${TAG}
    environment:
      - NGINX_BACKEND_PORT=5000
      - STATIC_DIR=/opt/app/dist/client
    ports:
      - 80:80
    depends_on:
      - bo-api-node
  bo-api-node:
    image: 564094729738.dkr.ecr.us-east-1.amazonaws.com/tg-bo/node:pr_${TAG}
    environment:
      - "NODE_ENV=production"
    ports:
      - "5000:5000"
networks:
  default:
    external:
      name: tg-internal-overlay
