version: '3'
services:
  bo-proxy-dev:
    image: 564094729738.dkr.ecr.us-east-1.amazonaws.com/tg-bo/nginx:dv_${TAG}
    environment:
      - NGINX_BACKEND_PORT=5000
      - STATIC_DIR=/opt/app/dist/client
    ports:
      - 80:80
    depends_on:
      - node1
  bo-api-node:
    image: 564094729738.dkr.ecr.us-east-1.amazonaws.com/tg-bo/node:dv_${TAG}
    environment:
      - "NODE_ENV=development"
    ports:
      - "5000:5000"
networks:
  default:
    external:
      name: olnw-tgbo
