enum EventType {
  HOTEL = 'HOTEL',
  POI = 'POI',
  DRIVING = 'DRIVING',
  TERMINAL = 'TERMINAL',
  ACTIVITY = 'ACTIVITY',
  CUSTOM = 'CUSTOM',
  DESTINATION = 'DESTINATION',



  DRIVING = 'DRIVING',
  PLACE = 'PLACE',
  CUSTOM = 'CUSTOM'
}

export default EventType;
